### ISSUE TITLE
Add Support for Images

### ISSUE THREAD

**Issue by torch2424** [torch2424/link-dump#31] opened 2015-09-14 00:07 UTC
Images should be auto embedded, especially things like imgur and things

**Comment by julianpoy** [comment] 2015-09-14 17:31
Before diving off the deep end with this, I believe we should discuss our methodology involving this. I think there might be an easier way for all of these specific items.

**Comment by julianpoy** [comment] 2015-09-14 17:34
Also, duplicate of #9. This should be added to #9's list, and closed.

**Comment by julianpoy** [comment] 2015-09-17 03:33
Closing this.

**Closed as completed by julianpoy** 2015-09-17 03:33 UTC
Labels: function
